from setuptools import setup


setup(
    name='pyCEDFS',
    version='0.1.6',
    author='Smestern',
    author_email='n/a',
    packages=['pyCEDFS'],
    url='https://github.com/smestern',
    license='MIT License',
    platforms='https://github.com/smestern',
    description='A python package to read data from CFS files generated by the signal software from CED systems',
    long_description='',
    download_url = 'https://github.com/user/reponame/archive/v_01.tar.gz',
    install_requires=[	
       'matplotlib>=2.1.0',
       'numpy>=1.17',
       'pynwb==1.4.0',
       'python_dateutil==2.8.1',
       'x_to_nwb==0.2.2'
	],
	include_package_data=True,
	package_data={
        
        "": ["*.dll"]},
    classifiers=[
    'Development Status :: 3 - Alpha',      
    'Intended Audience :: Developers',      
    'Topic :: Software Development ',
    'License :: OSI Approved :: MIT License',   
    'Programming Language :: Python :: 3',      
    'Programming Language :: Python :: 3.4',
    'Programming Language :: Python :: 3.5',
    'Programming Language :: Python :: 3.6',
         ],
)
